name: Scrape and Update KTC CSV

on:
  schedule:
    - cron: '0 6,18 * * *'  # Runs at 6AM and 6PM UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 tqdm

      - name: Run scraper
        run: |
          python ktc_scraper.py

      - name: Move CSV to docs folder
        run: |
          mkdir -p docs
          mv ktc.csv docs/ktc.csv

      - name: Commit and Push changes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add docs/ktc.csv
          git commit -m "Update KTC CSV" || echo "No changes to commit"
          git push origin main

